# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 798f8dbb11986c62315e7585e19aa85d2a707d39a3a15721a4aae534b542ec42abc854ecc8504d1175ef1d5d72741d427a1d0c6925580729ef0e676f23bfff7b

test:
  domain_name: example.com 
  secret_key_base: 6ddc3ce7d621ac90a59791aa627a2b114a5a990005bc98b1d3ba333cf6c018bc813448d0eeb4040ca1044df6e46c0906d024de8be41681e1bd79dfac3b7698b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
